manifest:
  defaults:
    revision: feat/battery-reporting
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: genteure
      url-base: https://github.com/Genteure
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: genteure
      revision: feat/battery-reporting
      import: app/west.yml
  self:
    path: config
